//
//  AvatarColors.m
//  Chatimate
//
//  Created by Nikki Durkin on 10/23/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "AvatarColors.h"


@implementation AvatarColors

#pragma mark Cache

static UIColor* _skinTone1 = nil;
static UIColor* _skinTone2 = nil;
static UIColor* _skinTone3 = nil;
static UIColor* _skinTone4 = nil;
static UIColor* _skinTone5 = nil;
static UIColor* _skinTone6 = nil;
static UIColor* _skinTone7 = nil;
static UIColor* _skinTone8 = nil;
static UIColor* _skinTone9 = nil;
static UIColor* _skinTone10 = nil;
static UIColor* _skinTone11 = nil;
static UIColor* _skinTone12 = nil;
static UIColor* _skinTone13 = nil;
static UIColor* _skinTone14 = nil;
static UIColor* _skinTone15 = nil;
static UIColor* _skinTone16 = nil;
static UIColor* _skinTone17 = nil;
static UIColor* _skinTone18 = nil;
static UIColor* _skinTone19 = nil;
static UIColor* _skinTone20 = nil;
static UIColor* _skinTone21 = nil;
static UIColor* _skinTone22 = nil;
static UIColor* _skinTone23 = nil;
static UIColor* _skinTone24 = nil;
static UIColor* _skinTone25 = nil;
static UIColor* _skinTone26 = nil;
static UIColor* _skinTone27 = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _skinTone1 = [UIColor colorWithRed: 1 green: 0.898 blue: 0.784 alpha: 1];
    _skinTone2 = [UIColor colorWithRed: 1 green: 0.855 blue: 0.745 alpha: 1];
    _skinTone3 = [UIColor colorWithRed: 1 green: 0.808 blue: 0.706 alpha: 1];
    _skinTone4 = [UIColor colorWithRed: 1 green: 0.765 blue: 0.667 alpha: 1];
    _skinTone5 = [UIColor colorWithRed: 0.941 green: 0.722 blue: 0.627 alpha: 1];
    _skinTone6 = [UIColor colorWithRed: 0.882 green: 0.675 blue: 0.588 alpha: 1];
    _skinTone7 = [UIColor colorWithRed: 0.824 green: 0.631 blue: 0.549 alpha: 1];
    _skinTone8 = [UIColor colorWithRed: 0.765 green: 0.584 blue: 0.51 alpha: 1];
    _skinTone9 = [UIColor colorWithRed: 0.706 green: 0.541 blue: 0.471 alpha: 1];
    _skinTone10 = [UIColor colorWithRed: 0.647 green: 0.494 blue: 0.431 alpha: 1];
    _skinTone11 = [UIColor colorWithRed: 0.588 green: 0.447 blue: 0.392 alpha: 1];
    _skinTone12 = [UIColor colorWithRed: 0.529 green: 0.404 blue: 0.353 alpha: 1];
    _skinTone13 = [UIColor colorWithRed: 0.471 green: 0.361 blue: 0.314 alpha: 1];
    _skinTone14 = [UIColor colorWithRed: 0.412 green: 0.314 blue: 0.275 alpha: 1];
    _skinTone15 = [UIColor colorWithRed: 0.353 green: 0.271 blue: 0.235 alpha: 1];
    _skinTone16 = [UIColor colorWithRed: 0.294 green: 0.224 blue: 0.196 alpha: 1];
    _skinTone17 = [UIColor colorWithRed: 0.235 green: 0.18 blue: 0.157 alpha: 1];
    _skinTone18 = [UIColor colorWithRed: 0.176 green: 0.133 blue: 0.118 alpha: 1];
    _skinTone19 = [UIColor colorWithRed: 1 green: 0.785 blue: 0.62 alpha: 1];
    _skinTone20 = [UIColor colorWithRed: 0.867 green: 0.667 blue: 0.514 alpha: 1];
    _skinTone21 = [UIColor colorWithRed: 0.858 green: 0.619 blue: 0.437 alpha: 1];
    _skinTone22 = [UIColor colorWithRed: 0.791 green: 0.543 blue: 0.354 alpha: 1];
    _skinTone23 = [UIColor colorWithRed: 0.672 green: 0.423 blue: 0.233 alpha: 1];
    _skinTone24 = [UIColor colorWithRed: 0.517 green: 0.3 blue: 0.134 alpha: 1];
    _skinTone25 = [UIColor colorWithRed: 0.381 green: 0.201 blue: 0.062 alpha: 1];
    _skinTone26 = [UIColor colorWithRed: 0.265 green: 0.122 blue: 0.013 alpha: 1];
    _skinTone27 = [UIColor colorWithRed: 0.206 green: 0.094 blue: 0.008 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)skinTone1 { return _skinTone1; }
+ (UIColor*)skinTone2 { return _skinTone2; }
+ (UIColor*)skinTone3 { return _skinTone3; }
+ (UIColor*)skinTone4 { return _skinTone4; }
+ (UIColor*)skinTone5 { return _skinTone5; }
+ (UIColor*)skinTone6 { return _skinTone6; }
+ (UIColor*)skinTone7 { return _skinTone7; }
+ (UIColor*)skinTone8 { return _skinTone8; }
+ (UIColor*)skinTone9 { return _skinTone9; }
+ (UIColor*)skinTone10 { return _skinTone10; }
+ (UIColor*)skinTone11 { return _skinTone11; }
+ (UIColor*)skinTone12 { return _skinTone12; }
+ (UIColor*)skinTone13 { return _skinTone13; }
+ (UIColor*)skinTone14 { return _skinTone14; }
+ (UIColor*)skinTone15 { return _skinTone15; }
+ (UIColor*)skinTone16 { return _skinTone16; }
+ (UIColor*)skinTone17 { return _skinTone17; }
+ (UIColor*)skinTone18 { return _skinTone18; }
+ (UIColor*)skinTone19 { return _skinTone19; }
+ (UIColor*)skinTone20 { return _skinTone20; }
+ (UIColor*)skinTone21 { return _skinTone21; }
+ (UIColor*)skinTone22 { return _skinTone22; }
+ (UIColor*)skinTone23 { return _skinTone23; }
+ (UIColor*)skinTone24 { return _skinTone24; }
+ (UIColor*)skinTone25 { return _skinTone25; }
+ (UIColor*)skinTone26 { return _skinTone26; }
+ (UIColor*)skinTone27 { return _skinTone27; }

#pragma mark Drawing Methods

+ (void)drawCanvas1;
{
}

@end
