//
//  AvatarColors.h
//  Chatimate
//
//  Created by Nikki Durkin on 10/23/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface AvatarColors : NSObject

// Colors
+ (UIColor*)skinTone1;
+ (UIColor*)skinTone2;
+ (UIColor*)skinTone3;
+ (UIColor*)skinTone4;
+ (UIColor*)skinTone5;
+ (UIColor*)skinTone6;
+ (UIColor*)skinTone7;
+ (UIColor*)skinTone8;
+ (UIColor*)skinTone9;
+ (UIColor*)skinTone10;
+ (UIColor*)skinTone11;
+ (UIColor*)skinTone12;
+ (UIColor*)skinTone13;
+ (UIColor*)skinTone14;
+ (UIColor*)skinTone15;
+ (UIColor*)skinTone16;
+ (UIColor*)skinTone17;
+ (UIColor*)skinTone18;
+ (UIColor*)skinTone19;
+ (UIColor*)skinTone20;
+ (UIColor*)skinTone21;
+ (UIColor*)skinTone22;
+ (UIColor*)skinTone23;
+ (UIColor*)skinTone24;
+ (UIColor*)skinTone25;
+ (UIColor*)skinTone26;
+ (UIColor*)skinTone27;

@end
