//
//  CHAvatarDrawingData.h
//  Chatimate
//
//  Created by Nikki Durkin on 10/25/14.
//  Copyright (c) 2014 (null). All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#import "CHCreateAvatar.h"

#define PATH @"Path"
#define FILL_COLOR @"Fill Color"


@interface CHAvatarDrawingData : NSObject



// Colors
+ (UIColor*)skinTone1;
+ (UIColor*)skinTone2;
+ (UIColor*)skinTone3;
+ (UIColor*)skinTone4;
+ (UIColor*)skinTone5;
+ (UIColor*)skinTone6;
+ (UIColor*)skinTone7;
+ (UIColor*)skinTone8;
+ (UIColor*)skinTone9;
+ (UIColor*)skinTone10;
+ (UIColor*)skinTone11;
+ (UIColor*)skinTone12;
+ (UIColor*)skinTone13;
+ (UIColor*)skinTone14;
+ (UIColor*)skinTone15;
+ (UIColor*)skinTone16;
+ (UIColor*)skinTone17;
+ (UIColor*)skinTone18;
+ (UIColor*)skinTone19;
+ (UIColor*)skinTone20;
+ (UIColor*)skinTone21;
+ (UIColor*)skinTone22;
+ (UIColor*)skinTone23;
+ (UIColor*)skinTone24;
+ (UIColor*)skinTone25;
+ (UIColor*)skinTone26;
+ (UIColor*)skinTone27;
+ (UIColor*)outlineColor;

//To draw an array of paths
+ (void)drawPaths:(NSMutableArray *)arrayOfPaths;
+ (void)drawOptions:(NSMutableDictionary *)options;

#pragma mark - Option Drawings

//Shoulders
+ (NSMutableArray *)drawShoulders:(NSMutableDictionary *)universalColors;

//Neck
+ (NSMutableArray *)drawNeck:(NSMutableDictionary *)universalColors;

//Upper Head
+ (NSMutableArray *)drawUpperHead:(NSMutableDictionary *)universalColors;

//Jaws
+ (NSMutableArray *)drawJaw1:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw2:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw3:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw4:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw5:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw6:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw7:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw8:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw9:(NSMutableDictionary *)universalColors;

//Ears
+ (NSMutableArray *)drawEars1:(NSMutableDictionary *)universalColors;


#pragma mark - Thumbnails

//Color thumbnails
+ (NSMutableArray *)drawColorThumbnail:(UIColor *)color;

//Jaw thumbnails
+ (NSMutableArray *)drawJaw1Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw2Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw3Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw4Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw5Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw6Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw7Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw8Thumbnail:(NSMutableDictionary *)universalColors;
+ (NSMutableArray *)drawJaw9Thumbnail:(NSMutableDictionary *)universalColors;

@end
